# Generated by Django 4.2 on 2023-05-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_space',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
