# Generated by Django 4.2 on 2023-05-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_property_title_alter_property_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.AddField(
            model_name='property',
            name='postcode',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='suburb',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
