# Generated by Django 4.2 on 2023-05-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0007_alter_property_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
