# Generated by Django 4.2 on 2023-05-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0008_alter_property_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/image/unknown_prop.png', upload_to='image/'),
        ),
    ]
