# Generated by Django 4.2 on 2023-05-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
