# Generated by Django 4.2.1 on 2023-05-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Createaccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='id',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='Email',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
