# Generated by Django 4.2.1 on 2023-05-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Createaccount', '0002_remove_accounts_id_alter_accounts_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='role',
            field=models.CharField(default='', max_length=10),
        ),
    ]
