<<<<<<< HEAD
# Generated by Django 4.2 on 2023-05-27 07:09
=======
# Generated by Django 4.2.1 on 2023-05-24 13:55
>>>>>>> a521c113ad8466310e9ea5aa6d6144318a4c3832

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Createaccount', '0003_accounts_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='setupprofilerenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(default='', max_length=20)),
                ('income', models.IntegerField(default='0')),
                ('reason', models.CharField(default='', max_length=250)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Createaccount.accounts')),
            ],
        ),
    ]
