# Generated by Django 4.2 on 2023-05-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_dob_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aboutme',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
