# Generated by Django 4.2 on 2023-05-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_user_amount_after_tax_user_income_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photoid',
            field=models.FileField(blank=True, upload_to='userphoto/'),
        ),
        migrations.AddField(
            model_name='user',
            name='secondid',
            field=models.FileField(blank=True, upload_to='userphoto/'),
        ),
    ]
