# Generated by Django 4.2 on 2023-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_property_bathroom_property_bedroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default='Title', max_length=400),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(default='Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='Description'),
        ),
    ]
