# Generated by Django 4.2 on 2023-05-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_remove_property_address_property_postcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
