# Generated by Django 4.2 on 2023-05-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_property_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.FileField(upload_to='image/'),
        ),
    ]
