# Generated by Django 4.2 on 2023-05-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0009_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='postcode',
            field=models.CharField(default='', max_length=4),
        ),
    ]
