# Generated by Django 4.2 on 2023-05-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0011_property_landlord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
